### YamlMime:ManagedReference
items:
- uid: Boyles.Tablazor.Configuration.TablerAssets
  commentId: T:Boyles.Tablazor.Configuration.TablerAssets
  id: TablerAssets
  parent: Boyles.Tablazor.Configuration
  children:
  - Boyles.Tablazor.Configuration.TablerAssets.#ctor
  - Boyles.Tablazor.Configuration.TablerAssets.FavIcon
  - Boyles.Tablazor.Configuration.TablerAssets.StyleSheets
  langs:
  - csharp
  - vb
  name: TablerAssets
  nameWithType: TablerAssets
  fullName: Boyles.Tablazor.Configuration.TablerAssets
  type: Class
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerAssets.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: TablerAssets
    path: ../Boyles.Tablazor/Configuration/TablerAssets.cs
    startLine: 2
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: public sealed class TablerAssets
    content.vb: Public NotInheritable Class TablerAssets
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Boyles.Tablazor.Configuration.TablerAssets.FavIcon
  commentId: P:Boyles.Tablazor.Configuration.TablerAssets.FavIcon
  id: FavIcon
  parent: Boyles.Tablazor.Configuration.TablerAssets
  langs:
  - csharp
  - vb
  name: FavIcon
  nameWithType: TablerAssets.FavIcon
  fullName: Boyles.Tablazor.Configuration.TablerAssets.FavIcon
  type: Property
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerAssets.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: FavIcon
    path: ../Boyles.Tablazor/Configuration/TablerAssets.cs
    startLine: 13
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: public string FavIcon { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FavIcon As String
  overload: Boyles.Tablazor.Configuration.TablerAssets.FavIcon*
- uid: Boyles.Tablazor.Configuration.TablerAssets.StyleSheets
  commentId: P:Boyles.Tablazor.Configuration.TablerAssets.StyleSheets
  id: StyleSheets
  parent: Boyles.Tablazor.Configuration.TablerAssets
  langs:
  - csharp
  - vb
  name: StyleSheets
  nameWithType: TablerAssets.StyleSheets
  fullName: Boyles.Tablazor.Configuration.TablerAssets.StyleSheets
  type: Property
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerAssets.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: StyleSheets
    path: ../Boyles.Tablazor/Configuration/TablerAssets.cs
    startLine: 15
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: public List<TablerAsset> StyleSheets { get; }
    parameters: []
    return:
      type: System.Collections.Generic.List{Boyles.Tablazor.Configuration.TablerAsset}
    content.vb: Public ReadOnly Property StyleSheets As List(Of TablerAsset)
  overload: Boyles.Tablazor.Configuration.TablerAssets.StyleSheets*
- uid: Boyles.Tablazor.Configuration.TablerAssets.#ctor
  commentId: M:Boyles.Tablazor.Configuration.TablerAssets.#ctor
  id: '#ctor'
  parent: Boyles.Tablazor.Configuration.TablerAssets
  langs:
  - csharp
  - vb
  name: TablerAssets()
  nameWithType: TablerAssets.TablerAssets()
  fullName: Boyles.Tablazor.Configuration.TablerAssets.TablerAssets()
  type: Constructor
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerAssets.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: .ctor
    path: ../Boyles.Tablazor/Configuration/TablerAssets.cs
    startLine: 17
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: public TablerAssets()
    content.vb: Public Sub New()
  overload: Boyles.Tablazor.Configuration.TablerAssets.#ctor*
  nameWithType.vb: TablerAssets.New()
  fullName.vb: Boyles.Tablazor.Configuration.TablerAssets.New()
  name.vb: New()
references:
- uid: Boyles.Tablazor.Configuration
  commentId: N:Boyles.Tablazor.Configuration
  href: Boyles.html
  name: Boyles.Tablazor.Configuration
  nameWithType: Boyles.Tablazor.Configuration
  fullName: Boyles.Tablazor.Configuration
  spec.csharp:
  - uid: Boyles
    name: Boyles
    href: Boyles.html
  - name: .
  - uid: Boyles.Tablazor
    name: Tablazor
    href: Boyles.Tablazor.html
  - name: .
  - uid: Boyles.Tablazor.Configuration
    name: Configuration
    href: Boyles.Tablazor.Configuration.html
  spec.vb:
  - uid: Boyles
    name: Boyles
    href: Boyles.html
  - name: .
  - uid: Boyles.Tablazor
    name: Tablazor
    href: Boyles.Tablazor.html
  - name: .
  - uid: Boyles.Tablazor.Configuration
    name: Configuration
    href: Boyles.Tablazor.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Boyles.Tablazor.Configuration.TablerAssets.FavIcon*
  commentId: Overload:Boyles.Tablazor.Configuration.TablerAssets.FavIcon
  href: Boyles.Tablazor.Configuration.TablerAssets.html#Boyles_Tablazor_Configuration_TablerAssets_FavIcon
  name: FavIcon
  nameWithType: TablerAssets.FavIcon
  fullName: Boyles.Tablazor.Configuration.TablerAssets.FavIcon
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Boyles.Tablazor.Configuration.TablerAssets.StyleSheets*
  commentId: Overload:Boyles.Tablazor.Configuration.TablerAssets.StyleSheets
  href: Boyles.Tablazor.Configuration.TablerAssets.html#Boyles_Tablazor_Configuration_TablerAssets_StyleSheets
  name: StyleSheets
  nameWithType: TablerAssets.StyleSheets
  fullName: Boyles.Tablazor.Configuration.TablerAssets.StyleSheets
- uid: System.Collections.Generic.List{Boyles.Tablazor.Configuration.TablerAsset}
  commentId: T:System.Collections.Generic.List{Boyles.Tablazor.Configuration.TablerAsset}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<TablerAsset>
  nameWithType: List<TablerAsset>
  fullName: System.Collections.Generic.List<Boyles.Tablazor.Configuration.TablerAsset>
  nameWithType.vb: List(Of TablerAsset)
  fullName.vb: System.Collections.Generic.List(Of Boyles.Tablazor.Configuration.TablerAsset)
  name.vb: List(Of TablerAsset)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Boyles.Tablazor.Configuration.TablerAsset
    name: TablerAsset
    href: Boyles.Tablazor.Configuration.TablerAsset.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Boyles.Tablazor.Configuration.TablerAsset
    name: TablerAsset
    href: Boyles.Tablazor.Configuration.TablerAsset.html
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Boyles.Tablazor.Configuration.TablerAssets.#ctor*
  commentId: Overload:Boyles.Tablazor.Configuration.TablerAssets.#ctor
  href: Boyles.Tablazor.Configuration.TablerAssets.html#Boyles_Tablazor_Configuration_TablerAssets__ctor
  name: TablerAssets
  nameWithType: TablerAssets.TablerAssets
  fullName: Boyles.Tablazor.Configuration.TablerAssets.TablerAssets
  nameWithType.vb: TablerAssets.New
  fullName.vb: Boyles.Tablazor.Configuration.TablerAssets.New
  name.vb: New
