### YamlMime:ManagedReference
items:
- uid: Boyles.Tablazor.Configuration.TablerAssetType
  commentId: T:Boyles.Tablazor.Configuration.TablerAssetType
  id: TablerAssetType
  parent: Boyles.Tablazor.Configuration
  children:
  - Boyles.Tablazor.Configuration.TablerAssetType.Font
  - Boyles.Tablazor.Configuration.TablerAssetType.Script
  - Boyles.Tablazor.Configuration.TablerAssetType.StyleSheet
  langs:
  - csharp
  - vb
  name: TablerAssetType
  nameWithType: TablerAssetType
  fullName: Boyles.Tablazor.Configuration.TablerAssetType
  type: Enum
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerAssetType.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: TablerAssetType
    path: ../Boyles.Tablazor/Configuration/TablerAssetType.cs
    startLine: 2
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: public enum TablerAssetType
    content.vb: Public Enum TablerAssetType
- uid: Boyles.Tablazor.Configuration.TablerAssetType.StyleSheet
  commentId: F:Boyles.Tablazor.Configuration.TablerAssetType.StyleSheet
  id: StyleSheet
  parent: Boyles.Tablazor.Configuration.TablerAssetType
  langs:
  - csharp
  - vb
  name: StyleSheet
  nameWithType: TablerAssetType.StyleSheet
  fullName: Boyles.Tablazor.Configuration.TablerAssetType.StyleSheet
  type: Field
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerAssetType.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: StyleSheet
    path: ../Boyles.Tablazor/Configuration/TablerAssetType.cs
    startLine: 4
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: StyleSheet = 0
    return:
      type: Boyles.Tablazor.Configuration.TablerAssetType
- uid: Boyles.Tablazor.Configuration.TablerAssetType.Script
  commentId: F:Boyles.Tablazor.Configuration.TablerAssetType.Script
  id: Script
  parent: Boyles.Tablazor.Configuration.TablerAssetType
  langs:
  - csharp
  - vb
  name: Script
  nameWithType: TablerAssetType.Script
  fullName: Boyles.Tablazor.Configuration.TablerAssetType.Script
  type: Field
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerAssetType.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: Script
    path: ../Boyles.Tablazor/Configuration/TablerAssetType.cs
    startLine: 5
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: Script = 1
    return:
      type: Boyles.Tablazor.Configuration.TablerAssetType
- uid: Boyles.Tablazor.Configuration.TablerAssetType.Font
  commentId: F:Boyles.Tablazor.Configuration.TablerAssetType.Font
  id: Font
  parent: Boyles.Tablazor.Configuration.TablerAssetType
  langs:
  - csharp
  - vb
  name: Font
  nameWithType: TablerAssetType.Font
  fullName: Boyles.Tablazor.Configuration.TablerAssetType.Font
  type: Field
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerAssetType.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: Font
    path: ../Boyles.Tablazor/Configuration/TablerAssetType.cs
    startLine: 6
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: Font = 2
    return:
      type: Boyles.Tablazor.Configuration.TablerAssetType
references:
- uid: Boyles.Tablazor.Configuration
  commentId: N:Boyles.Tablazor.Configuration
  href: Boyles.html
  name: Boyles.Tablazor.Configuration
  nameWithType: Boyles.Tablazor.Configuration
  fullName: Boyles.Tablazor.Configuration
  spec.csharp:
  - uid: Boyles
    name: Boyles
    href: Boyles.html
  - name: .
  - uid: Boyles.Tablazor
    name: Tablazor
    href: Boyles.Tablazor.html
  - name: .
  - uid: Boyles.Tablazor.Configuration
    name: Configuration
    href: Boyles.Tablazor.Configuration.html
  spec.vb:
  - uid: Boyles
    name: Boyles
    href: Boyles.html
  - name: .
  - uid: Boyles.Tablazor
    name: Tablazor
    href: Boyles.Tablazor.html
  - name: .
  - uid: Boyles.Tablazor.Configuration
    name: Configuration
    href: Boyles.Tablazor.Configuration.html
- uid: Boyles.Tablazor.Configuration.TablerAssetType
  commentId: T:Boyles.Tablazor.Configuration.TablerAssetType
  parent: Boyles.Tablazor.Configuration
  href: Boyles.Tablazor.Configuration.TablerAssetType.html
  name: TablerAssetType
  nameWithType: TablerAssetType
  fullName: Boyles.Tablazor.Configuration.TablerAssetType
