### YamlMime:ManagedReference
items:
- uid: Boyles.Tablazor.Configuration.TablerOptions
  commentId: T:Boyles.Tablazor.Configuration.TablerOptions
  id: TablerOptions
  parent: Boyles.Tablazor.Configuration
  children:
  - Boyles.Tablazor.Configuration.TablerOptions.Assets
  - Boyles.Tablazor.Configuration.TablerOptions.DefaultVersion
  - Boyles.Tablazor.Configuration.TablerOptions.Version
  langs:
  - csharp
  - vb
  name: TablerOptions
  nameWithType: TablerOptions
  fullName: Boyles.Tablazor.Configuration.TablerOptions
  type: Class
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerOptions.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: TablerOptions
    path: ../Boyles.Tablazor/Configuration/TablerOptions.cs
    startLine: 2
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: public sealed class TablerOptions
    content.vb: Public NotInheritable Class TablerOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Boyles.Tablazor.Configuration.TablerOptions.DefaultVersion
  commentId: F:Boyles.Tablazor.Configuration.TablerOptions.DefaultVersion
  id: DefaultVersion
  parent: Boyles.Tablazor.Configuration.TablerOptions
  langs:
  - csharp
  - vb
  name: DefaultVersion
  nameWithType: TablerOptions.DefaultVersion
  fullName: Boyles.Tablazor.Configuration.TablerOptions.DefaultVersion
  type: Field
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerOptions.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: DefaultVersion
    path: ../Boyles.Tablazor/Configuration/TablerOptions.cs
    startLine: 4
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: public const string DefaultVersion = "1.0.0-beta20"
    return:
      type: System.String
    content.vb: Public Const DefaultVersion As String = "1.0.0-beta20"
- uid: Boyles.Tablazor.Configuration.TablerOptions.Version
  commentId: P:Boyles.Tablazor.Configuration.TablerOptions.Version
  id: Version
  parent: Boyles.Tablazor.Configuration.TablerOptions
  langs:
  - csharp
  - vb
  name: Version
  nameWithType: TablerOptions.Version
  fullName: Boyles.Tablazor.Configuration.TablerOptions.Version
  type: Property
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerOptions.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: Version
    path: ../Boyles.Tablazor/Configuration/TablerOptions.cs
    startLine: 6
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: public string Version { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Version As String
  overload: Boyles.Tablazor.Configuration.TablerOptions.Version*
- uid: Boyles.Tablazor.Configuration.TablerOptions.Assets
  commentId: P:Boyles.Tablazor.Configuration.TablerOptions.Assets
  id: Assets
  parent: Boyles.Tablazor.Configuration.TablerOptions
  langs:
  - csharp
  - vb
  name: Assets
  nameWithType: TablerOptions.Assets
  fullName: Boyles.Tablazor.Configuration.TablerOptions.Assets
  type: Property
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/TablerOptions.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: Assets
    path: ../Boyles.Tablazor/Configuration/TablerOptions.cs
    startLine: 8
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: public TablerAssets Assets { get; }
    parameters: []
    return:
      type: Boyles.Tablazor.Configuration.TablerAssets
    content.vb: Public ReadOnly Property Assets As TablerAssets
  overload: Boyles.Tablazor.Configuration.TablerOptions.Assets*
references:
- uid: Boyles.Tablazor.Configuration
  commentId: N:Boyles.Tablazor.Configuration
  href: Boyles.html
  name: Boyles.Tablazor.Configuration
  nameWithType: Boyles.Tablazor.Configuration
  fullName: Boyles.Tablazor.Configuration
  spec.csharp:
  - uid: Boyles
    name: Boyles
    href: Boyles.html
  - name: .
  - uid: Boyles.Tablazor
    name: Tablazor
    href: Boyles.Tablazor.html
  - name: .
  - uid: Boyles.Tablazor.Configuration
    name: Configuration
    href: Boyles.Tablazor.Configuration.html
  spec.vb:
  - uid: Boyles
    name: Boyles
    href: Boyles.html
  - name: .
  - uid: Boyles.Tablazor
    name: Tablazor
    href: Boyles.Tablazor.html
  - name: .
  - uid: Boyles.Tablazor.Configuration
    name: Configuration
    href: Boyles.Tablazor.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Boyles.Tablazor.Configuration.TablerOptions.Version*
  commentId: Overload:Boyles.Tablazor.Configuration.TablerOptions.Version
  href: Boyles.Tablazor.Configuration.TablerOptions.html#Boyles_Tablazor_Configuration_TablerOptions_Version
  name: Version
  nameWithType: TablerOptions.Version
  fullName: Boyles.Tablazor.Configuration.TablerOptions.Version
- uid: Boyles.Tablazor.Configuration.TablerOptions.Assets*
  commentId: Overload:Boyles.Tablazor.Configuration.TablerOptions.Assets
  href: Boyles.Tablazor.Configuration.TablerOptions.html#Boyles_Tablazor_Configuration_TablerOptions_Assets
  name: Assets
  nameWithType: TablerOptions.Assets
  fullName: Boyles.Tablazor.Configuration.TablerOptions.Assets
- uid: Boyles.Tablazor.Configuration.TablerAssets
  commentId: T:Boyles.Tablazor.Configuration.TablerAssets
  parent: Boyles.Tablazor.Configuration
  href: Boyles.Tablazor.Configuration.TablerAssets.html
  name: TablerAssets
  nameWithType: TablerAssets
  fullName: Boyles.Tablazor.Configuration.TablerAssets
