### YamlMime:ManagedReference
items:
- uid: Boyles.Tablazor.Configuration
  commentId: N:Boyles.Tablazor.Configuration
  id: Boyles.Tablazor.Configuration
  children:
  - Boyles.Tablazor.Configuration.CdnOptions
  - Boyles.Tablazor.Configuration.TablerAsset
  - Boyles.Tablazor.Configuration.TablerAssetType
  - Boyles.Tablazor.Configuration.TablerAssets
  - Boyles.Tablazor.Configuration.TablerOptions
  langs:
  - csharp
  - vb
  name: Boyles.Tablazor.Configuration
  nameWithType: Boyles.Tablazor.Configuration
  fullName: Boyles.Tablazor.Configuration
  type: Namespace
  assemblies:
  - Boyles.Tablazor
references:
- uid: Boyles.Tablazor.Configuration.CdnOptions
  commentId: T:Boyles.Tablazor.Configuration.CdnOptions
  parent: Boyles.Tablazor.Configuration
  href: Boyles.Tablazor.Configuration.CdnOptions.html
  name: CdnOptions
  nameWithType: CdnOptions
  fullName: Boyles.Tablazor.Configuration.CdnOptions
- uid: Boyles.Tablazor.Configuration.TablerAsset
  commentId: T:Boyles.Tablazor.Configuration.TablerAsset
  href: Boyles.Tablazor.Configuration.TablerAsset.html
  name: TablerAsset
  nameWithType: TablerAsset
  fullName: Boyles.Tablazor.Configuration.TablerAsset
- uid: Boyles.Tablazor.Configuration.TablerAssets
  commentId: T:Boyles.Tablazor.Configuration.TablerAssets
  parent: Boyles.Tablazor.Configuration
  href: Boyles.Tablazor.Configuration.TablerAssets.html
  name: TablerAssets
  nameWithType: TablerAssets
  fullName: Boyles.Tablazor.Configuration.TablerAssets
- uid: Boyles.Tablazor.Configuration.TablerAssetType
  commentId: T:Boyles.Tablazor.Configuration.TablerAssetType
  parent: Boyles.Tablazor.Configuration
  href: Boyles.Tablazor.Configuration.TablerAssetType.html
  name: TablerAssetType
  nameWithType: TablerAssetType
  fullName: Boyles.Tablazor.Configuration.TablerAssetType
- uid: Boyles.Tablazor.Configuration.TablerOptions
  commentId: T:Boyles.Tablazor.Configuration.TablerOptions
  href: Boyles.Tablazor.Configuration.TablerOptions.html
  name: TablerOptions
  nameWithType: TablerOptions
  fullName: Boyles.Tablazor.Configuration.TablerOptions
- uid: Boyles.Tablazor.Configuration
  commentId: N:Boyles.Tablazor.Configuration
  href: Boyles.html
  name: Boyles.Tablazor.Configuration
  nameWithType: Boyles.Tablazor.Configuration
  fullName: Boyles.Tablazor.Configuration
  spec.csharp:
  - uid: Boyles
    name: Boyles
    href: Boyles.html
  - name: .
  - uid: Boyles.Tablazor
    name: Tablazor
    href: Boyles.Tablazor.html
  - name: .
  - uid: Boyles.Tablazor.Configuration
    name: Configuration
    href: Boyles.Tablazor.Configuration.html
  spec.vb:
  - uid: Boyles
    name: Boyles
    href: Boyles.html
  - name: .
  - uid: Boyles.Tablazor
    name: Tablazor
    href: Boyles.Tablazor.html
  - name: .
  - uid: Boyles.Tablazor.Configuration
    name: Configuration
    href: Boyles.Tablazor.Configuration.html
