### YamlMime:ManagedReference
items:
- uid: Boyles.Tablazor.Configuration.CdnOptions
  commentId: T:Boyles.Tablazor.Configuration.CdnOptions
  id: CdnOptions
  parent: Boyles.Tablazor.Configuration
  children:
  - Boyles.Tablazor.Configuration.CdnOptions.None
  - Boyles.Tablazor.Configuration.CdnOptions.UseCdnForBoth
  - Boyles.Tablazor.Configuration.CdnOptions.UseCdnForDev
  - Boyles.Tablazor.Configuration.CdnOptions.UseCdnForProd
  langs:
  - csharp
  - vb
  name: CdnOptions
  nameWithType: CdnOptions
  fullName: Boyles.Tablazor.Configuration.CdnOptions
  type: Enum
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/CdnOptions.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: CdnOptions
    path: ../Boyles.Tablazor/Configuration/CdnOptions.cs
    startLine: 2
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: public enum CdnOptions
    content.vb: Public Enum CdnOptions
- uid: Boyles.Tablazor.Configuration.CdnOptions.None
  commentId: F:Boyles.Tablazor.Configuration.CdnOptions.None
  id: None
  parent: Boyles.Tablazor.Configuration.CdnOptions
  langs:
  - csharp
  - vb
  name: None
  nameWithType: CdnOptions.None
  fullName: Boyles.Tablazor.Configuration.CdnOptions.None
  type: Field
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/CdnOptions.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: None
    path: ../Boyles.Tablazor/Configuration/CdnOptions.cs
    startLine: 4
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: None = 0
    return:
      type: Boyles.Tablazor.Configuration.CdnOptions
- uid: Boyles.Tablazor.Configuration.CdnOptions.UseCdnForDev
  commentId: F:Boyles.Tablazor.Configuration.CdnOptions.UseCdnForDev
  id: UseCdnForDev
  parent: Boyles.Tablazor.Configuration.CdnOptions
  langs:
  - csharp
  - vb
  name: UseCdnForDev
  nameWithType: CdnOptions.UseCdnForDev
  fullName: Boyles.Tablazor.Configuration.CdnOptions.UseCdnForDev
  type: Field
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/CdnOptions.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: UseCdnForDev
    path: ../Boyles.Tablazor/Configuration/CdnOptions.cs
    startLine: 5
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: UseCdnForDev = 1
    return:
      type: Boyles.Tablazor.Configuration.CdnOptions
- uid: Boyles.Tablazor.Configuration.CdnOptions.UseCdnForProd
  commentId: F:Boyles.Tablazor.Configuration.CdnOptions.UseCdnForProd
  id: UseCdnForProd
  parent: Boyles.Tablazor.Configuration.CdnOptions
  langs:
  - csharp
  - vb
  name: UseCdnForProd
  nameWithType: CdnOptions.UseCdnForProd
  fullName: Boyles.Tablazor.Configuration.CdnOptions.UseCdnForProd
  type: Field
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/CdnOptions.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: UseCdnForProd
    path: ../Boyles.Tablazor/Configuration/CdnOptions.cs
    startLine: 6
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: UseCdnForProd = 2
    return:
      type: Boyles.Tablazor.Configuration.CdnOptions
- uid: Boyles.Tablazor.Configuration.CdnOptions.UseCdnForBoth
  commentId: F:Boyles.Tablazor.Configuration.CdnOptions.UseCdnForBoth
  id: UseCdnForBoth
  parent: Boyles.Tablazor.Configuration.CdnOptions
  langs:
  - csharp
  - vb
  name: UseCdnForBoth
  nameWithType: CdnOptions.UseCdnForBoth
  fullName: Boyles.Tablazor.Configuration.CdnOptions.UseCdnForBoth
  type: Field
  source:
    remote:
      path: src/Boyles.Tablazor/Configuration/CdnOptions.cs
      branch: dev
      repo: https://github.com/wayneboyles/tablazor.git
    id: UseCdnForBoth
    path: ../Boyles.Tablazor/Configuration/CdnOptions.cs
    startLine: 7
  assemblies:
  - Boyles.Tablazor
  namespace: Boyles.Tablazor.Configuration
  syntax:
    content: UseCdnForBoth = 3
    return:
      type: Boyles.Tablazor.Configuration.CdnOptions
references:
- uid: Boyles.Tablazor.Configuration
  commentId: N:Boyles.Tablazor.Configuration
  href: Boyles.html
  name: Boyles.Tablazor.Configuration
  nameWithType: Boyles.Tablazor.Configuration
  fullName: Boyles.Tablazor.Configuration
  spec.csharp:
  - uid: Boyles
    name: Boyles
    href: Boyles.html
  - name: .
  - uid: Boyles.Tablazor
    name: Tablazor
    href: Boyles.Tablazor.html
  - name: .
  - uid: Boyles.Tablazor.Configuration
    name: Configuration
    href: Boyles.Tablazor.Configuration.html
  spec.vb:
  - uid: Boyles
    name: Boyles
    href: Boyles.html
  - name: .
  - uid: Boyles.Tablazor
    name: Tablazor
    href: Boyles.Tablazor.html
  - name: .
  - uid: Boyles.Tablazor.Configuration
    name: Configuration
    href: Boyles.Tablazor.Configuration.html
- uid: Boyles.Tablazor.Configuration.CdnOptions
  commentId: T:Boyles.Tablazor.Configuration.CdnOptions
  parent: Boyles.Tablazor.Configuration
  href: Boyles.Tablazor.Configuration.CdnOptions.html
  name: CdnOptions
  nameWithType: CdnOptions
  fullName: Boyles.Tablazor.Configuration.CdnOptions
