
$OutputPath = "$PSScriptRoot\IconsClass.cs"     # ToDo: Change this to the project directory
$Namespace = "Tablazor.Icons"

$RepoOwner = "tabler"
$RepoName = "tabler-icons"
$ApiBase = "https://api.github.com/repos/$repoOwner/$repoName"

$Counter = 0

$OutlineIconData = @()
$FilledIconData = @()

$ErrorActionPreference = "Stop"

function Get-CSharpPropertyName {
    [CmdletBinding()]
    param(
        [string] $fileName
    )
    
    $name = [System.IO.Path]::GetFileNameWithoutExtension($fileName)
    
    # Convert kebab-case to PascalCase
    $parts = $name -split '-'
    $pascalCase = ($parts | ForEach-Object { 
        $_.Substring(0,1).ToUpper() + $_.Substring(1).ToLower() 
    }) -join ''
    
    # Handle names starting with numbers
    if ($pascalCase -match '^\d') {
        $pascalCase = "Icon$pascalCase"
    }
    
    return $pascalCase
}

function Get-SvgPath {
    [CmdletBinding()]
    param(
        [System.Xml.XmlDocument] $svgContent
    )
    
    # Extract path d attribute(s)
    $paths = [regex]::Matches($svgContent.InnerXml, '<path[^>]*\sd="([^"]*)"')
    
    if ($paths.Count -eq 0) {
        return $null
    }
    
    # Combine all paths if multiple exist
    $pathData = ($paths | ForEach-Object { $_.Groups[1].Value }) -join ' '
    return $pathData
}

function Get-IconData {
    [CmdletBinding()]
    param(
        [object] $icon,
        [string] $type
    )
    
    try {
        $svgContent = Invoke-RestMethod -Uri $icon.download_url -UseBasicParsing
        $path = Get-SvgPath -svgContent $svgContent
        
        if ($path) {
            $propName = Get-CSharpPropertyName -fileName $icon.name
            return @{
                Name = $propName
                Path = $path
                OriginalName = $icon.name
            }
        }
    }
    catch {
        Write-Warning "Failed to process $($icon.name): $_"
    }
    
    return $null
}

Write-Host "Tablazor Icons C# Class Generator" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan

Write-Host "`nFetching repository information..." -ForegroundColor Yellow

# Get the default branch
$RepoInfo = Invoke-RestMethod -Uri $ApiBase
$DefaultBranch = $RepoInfo.default_branch

# Fetch icons from both directories
$OutlineUrl = "$ApiBase/contents/icons/outline?ref=$DefaultBranch"
$FilledUrl = "$ApiBase/contents/icons/filled?ref=$DefaultBranch"

Write-Host "Downloading Outline icons..." -ForegroundColor Yellow
$OutlineIcons = Invoke-RestMethod -Uri $OutlineUrl

Write-Host "Downloading Filled icons..." -ForegroundColor Yellow
$FilledIcons = Invoke-RestMethod -Uri $FilledUrl

Write-Host "`nProcessing icons..." -ForegroundColor Yellow

$Counter = 0

foreach ($icon in $outlineIcons | Where-Object { $_.name -like "*.svg" }) {
    $counter++

    if ($counter % 100 -eq 0) {
        Write-Host "  Processed $counter outline icons..." -ForegroundColor Gray
    }
    
    $data = Get-IconData -icon $icon -type "Outline"
    if ($data) {
        $OutlineIconData += $data
    }
}

Write-Host "  Total Outline icons processed: $($OutlineIconData.Count)" -ForegroundColor Green
$Counter = 0

foreach ($icon in $filledIcons | Where-Object { $_.name -like "*.svg" }) {
    $counter++

    if ($counter % 100 -eq 0) {
        Write-Host "  Processed $counter filled icons..." -ForegroundColor Gray
    }
    
    $data = Get-IconData -icon $icon -type "Filled"
    if ($data) {
        $FilledIconData += $data
    }
}

Write-Host "  Total Filled icons processed: $($filledIconData.Count)" -ForegroundColor Green

Write-Host "`nGenerating C# class..." -ForegroundColor Yellow

$CSharpCode = @"
// <auto-generated>
//     This code was generated by Tablazor Icons Generator Script
//     Generated on: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
//     Outline Icons: $($OutlineIconData.Count)
//     Filled Icons: $($FilledIconData.Count)
// </auto-generated>

namespace $Namespace
{
    /// <summary>
    /// Static class containing Tabler Icons SVG path data
    /// </summary>
    public static class TablazorIcons   
    {
        /// <summary>
        /// Tabler Outline Icons - SVG path data for outline style icons
        /// </summary>
        public static class Outline
        {
"@

# Add outline icon properties
foreach ($icon in ($OutlineIconData | Sort-Object Name)) {
    $escapedPath = $icon.Path -replace '"', '\"'
    $csharpCode += @"

            /// <summary>Icon: $($icon.OriginalName)</summary>
            public const string $($icon.Name) = "$escapedPath";
             
"@
}

$csharpCode += @"

        }

        /// <summary>
        /// Tabler Filled Icons - SVG path data for filled style icons
        /// </summary>
        public static class Filled
        {
"@

# Add filled icon properties
foreach ($icon in ($FilledIconData | Sort-Object Name)) {
    $escapedPath = $icon.Path -replace '"', '\"'
    $csharpCode += @"

            /// <summary>Icon: $($icon.OriginalName)</summary>
            public const string $($icon.Name) = "$escapedPath";
             
"@
}

$csharpCode += @"

        }
    }

    /// <summary>
    /// Helper class for rendering Tabler Icons as SVG
    /// </summary>
    public static class TablazorIconRenderer
    {
        /// <summary>
        /// Renders an icon path as a complete SVG element
        /// Automatically detects if the icon is filled or outline based on the path data
        /// </summary>
        /// <param name="pathData">The SVG path data</param>
        /// <param name="size">Icon size (default: 24)</param>
        /// <param name="strokeWidth">Stroke width for outline icons (default: 2)</param>
        /// <param name="color">Icon color (default: currentColor)</param>
        /// <param name="cssClass">Optional CSS class</param>
        /// <returns>Complete SVG markup</returns>
        public static string Render(string pathData, int size = 24, int strokeWidth = 2, string color = "currentColor", string cssClass = "")
        {
            var classAttr = string.IsNullOrEmpty(cssClass) ? "" : $" class=\"{cssClass}\"";
            
            // Detect if this is a filled icon by checking if it exists in the filled icons
            bool isFilled = IsFilledIcon(pathData);
            
            if (isFilled)
            {
                // Filled icon: use fill, no stroke
                return $"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{size}\" height=\"{size}\" viewBox=\"0 0 24 24\" fill=\"{color}\" stroke=\"none\"{classAttr}><path d=\"{pathData}\"/></svg>";
            }
            else
            {
                // Outline icon: use stroke, no fill
                return $"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{size}\" height=\"{size}\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"{color}\" stroke-width=\"{strokeWidth}\" stroke-linecap=\"round\" stroke-linejoin=\"round\"{classAttr}><path d=\"{pathData}\"/></svg>";
            }
        }

        private static bool IsFilledIcon(string pathData)
        {
            // Check if the path data matches any filled icon

            var filledIconsType = typeof(TablazorIcons.Filled);
            var properties = filledIconsType.GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);
            
            foreach (var prop in properties)
            {
                if (prop.GetValue(null) as string == pathData)
                {
                    return true;
                }
            }
            
            return false;
        }
    }
}
"@

# Write to file
$CSharpCode | Out-File -FilePath $OutputPath -Encoding UTF8